services:
  - type: web
    name: kyro-anime
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: KYRO_PASSWORD
        value: kyro2026
      - key: KYRO_OWNER_KEY
        generateValue: true
      - key: KYRO_STAFF_KEY
        generateValue: true
      - key: KYRO_ALLOWED_ORIGINS
        value: https://kyro-anime.onrender.com
